### ISSUE TITLE
Spieler Bewegung angenehmer machen

### ISSUE THREAD

**Issue by Clichee** [JValentinB/Singularity_Computer-Game-Course#10]
Bisher sind die Bewegungen vom Spieler etwas langsam? Fühlen sich nicht so angenehm an zum bewegen.
Etwas Geschwindigkeit erhöhen, zusammen mit der Animationsgeschwindigkeit, damit diese synchron bleiben.

**Comment by yunutycravatty** [comment]
Ist das mittlerweile fertig?

**Comment by Clichee** [comment]
Ich würde sagen, dass der korrekte Absprung bei der Springanimation dazugehört und des ist noch nicht gefixt, also ne.

**Comment by JValentinB** [comment]
Ich arbeite gerade an neuen Animationen, versuche das zu fixen.
