### ISSUE TITLE
Level Design: Bossgegner für Forest

### ISSUE THREAD

**Issue by Clichee** [JValentinB/Singularity_Computer-Game-Course#27]
Ideen für moveset planen.
Implementieren von verschiedenen Attacken.
Bewegungen abhängig vom Spieler.
Blender Design für Boss und Attacken.
Partikel für Attacken.
Sound für Attacken, Movement.

Implementierung mithilfe der Enemy class.

**Comment by yunutycravatty** [comment]
Idee/Fortschritt hier rein schreiben
