### ISSUE TITLE
Spieler sollte auf allen vieren rennen

### ISSUE THREAD

**Issue by Clichee** [JValentinB/Singularity_Computer-Game-Course#9]
Neue Animation in Blender erstellen für das Rennen und implementieren, sodass diese ab einer gewissen Geschwindigkeit genutzt wird.

**Comment by JValentinB** [comment]
Bei meinem ersten Ottermodel hab ich das so ungefähr gemacht. Gehanimation war auf zwei Beinen und gerannt ist er auf allen vieren.
